"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let color = "blue";
let fullName = 'John Doe';
let age = 30;
let sentence = `Hello, my name is ${fullName} and I'll be ${age + 1} next year.`;
console.log("color: " + color);
console.log("fullName: " + fullName);
console.log("age: " + age);
console.log("sentence: " + sentence);
